### PR TITLE
Added support for repeated field query params

### PR DESCRIPTION
**Pull request by gfecher**

### CODE REVIEW

**Comment by Xorlev** [comment]
This looks great! Thanks for the contribution. :)

**Comment by gfecher** [comment]
Thank you for creating the project in the first place!
I am evangelising gRPC at my company and to ease migration I will be relying heavily on this.
We're a dropwizard shop and I'm guessing this is exactly why you created this project, too.
I'm planning a number of other improvements, like being able to run the protoc plugin under Windows and streaming, I'd appreciate it if you could look at my pull requests when they're ready.

**Comment by Xorlev** [comment]
Exactly right. Actually, server streaming already works if you check out #14 (though it's a WIP). I'm happy to prioritize merging server streaming if it's of use to you now.

**Comment by Xorlev** [comment]
> I'm planning a number of other improvements, like being able to run the protoc plugin under Windows

I think this should just be a matter of publishing the appropriate artifact name. https://github.com/Xorlev/grpc-jersey/blob/master/build.gradle#L156-L183

**Comment by gfecher** [comment]
Thanks, it worked a treat.

I have a number of questions (I'm new to gRPC), maybe you can help.

Now I'm trying to get swagger (and swagger-ui) going with the generated resource. Do you have any suggestions? So far I found an incredibly hacky way of injecting in the @Api annotation at runtime so that swagger discover it (based on https://stackoverflow.com/a/30287201/8483863).

My other question is a bit more general: I want the gRPC server exposed as well as the REST interface. For this I created 2 `Server`s, one built with a normal NettyServerBuilder and the other with an InProcessServerBuilder and added the same gRPC service implementation instance to both. 
The stub passed to the generated JerseyResource uses an InProcessChannel for the latter with a directExecutor (I'm guessing threading is handled by the Jersey server itself, so this is fine).
Is this the right way to do it? Or should the stub use a NettyChannelBuilder to connect to the netty-based Server?

Many thanks,
Feso (pronounced Fesho)

**Comment by Xorlev** [comment]
1) Swagger

I'd support a code generation option to emit Swagger annotations. Like the HttpRule extension that the protoc extension leverages, you could add an extension which lets you define the rest of the Swagger metadata. The [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/options/openapiv2.proto) project does exactly this.

2) https://github.com/Xorlev/grpc-jersey#operation-modes I have an example for a "dual stack" server. It has a single executor used to process requests from HTTP (via an InProcessChannel to avoid protobuf/HTTP2 overhead) as well as via gRPC.

**Pull request merged**
